# Generated by Django 5.1.6 on 2025-02-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_myuser_date_of_birth_alter_myuser_rgpd_consent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='rgpd_consent',
        ),
        migrations.AddField(
            model_name='myuser',
            name='can_be_contacted',
            field=models.BooleanField(default=False, verbose_name="J'accepte d'être contacté."),
        ),
        migrations.AddField(
            model_name='myuser',
            name='can_data_be_shared',
            field=models.BooleanField(default=False, verbose_name="J'accepte de partager mes données."),
        ),
    ]
